Dutch Translate
Kr0oked/Compass pull request #5
Opened 2021-05-01 12:40 UTC by timnea

I added the Dutch translation to the app.

v1.0

2021-05-02 19:10 UTC, Kr0oked requested changes
Thanks a lot for the translation!
In the latest commit a new string 'action_screen_rotation' was adeded, could you include this one in the translation?
And the string 'compass_rose_image_description'  is not translated. Its not an important one but then its complete.

2021-05-02 23:08 UTC, timnea commented
I forgot about the line "compass_rose_image_description" but it is all translated now.

2021-05-03 19:04 UTC, Kr0oked requested changes
I've noticed one small copy paste error. But then it's ready to submit.

2021-05-03 19:04 UTC, Kr0oked commented on app/src/main/res/values-nl/strings.xml
> +?xml version="1.0" encoding="utf-8"?>
First character '<' missing.
It should be: <?xml version="1.0" encoding="utf-8"?>

2021-05-06 20:42 UTC, closed without merging