Added hungarian translation
Kr0oked/Compass pull request #63
Opened 2023-11-09 09:32 UTC by titanicbobo

2023-11-11 16:24 UTC, Kr0oked requested changes
Thanks for providing the hungarian translation.
I really appreciate that.
There are two things in the strings.xml that we could improve.

And could you also provide translations for the texts of the app store? You can find them in the fastlane/android directory. You just have to provide translated versions for the files full_description.txt, short_description.txt and title.txt like in the other directories there . I will take care of the rest.

Thanks in advance!
Regards

2023-11-11 16:24 UTC, Kr0oked commented on app/src/main/res/values-hu/strings.xml
> +    <string name="access_location_permission_denied">Missing permission to access location. Falling back to magnetic north.</string>
access_location_permission_denied not translated

2023-11-11 16:24 UTC, Kr0oked commented on app/src/main/res/values-hu/strings.xml
> +    <string name="source_code_name" translatable="false">GitHub</string>
You can delete all the strings with translatable="false" from your file.

2023-11-11 18:13 UTC, titanicbobo commented
Thank you for your feedback! I fixed up those things you requested in strings.xml and I added those three files translated files to fastlane.

2023-11-12 16:43 UTC, Kr0oked approved these changes
Thanks for doing the adjustments.
The translation will be included in the next release, but there is not yet a plan when that will be.

2023-11-12 16:43 UTC, merged